### ISSUE TITLE
Please add install instructions to cmake scripts

### ISSUE THREAD

**Issue by yurivict** [QMCPACK/qmcpack#1017]
Currently it doesn't install anything, and it isn't clear what should it install.

**Comment by prckent** [comment]
We do not yet support an "install" of QMCPACK, although it would be feasible. Yours is the first request. QMCPACK has a variety of build options and in practice needs support scripts, which we would have to accommodate.

Have you been able to build and run QMCPACK successfully? What operating system and environment are you trying to "install" on? What would be most helpful? Historically we have not had requests, likely because in HPC environments users typically have no access to standard installation directories.

**Comment by yurivict** [comment]
> Have you been able to build and run QMCPACK successfully? What operating system and environment are you trying to "install" on? What would be most helpful? Historically we have not had requests, likely because in HPC environments users typically have no access to standard installation directories.

I asked for the FreeBSD port, was in the process of creating it. Eventually I had to guess what files to install: https://svnweb.freebsd.org/ports/head/science/qmcpack/Makefile?revision=477635&view=markup

It installs executables that are in bin/: convert4qmc extract-eshdf-kvectors getSupercell qmcpack

I didn't have a chance to run it myself yet. I noticed that FreeBSD is the first system to have a port for qmcpack. All systems (Debian/Redhat/Arch/etc) will have the same question when they will want to create ports.

**Comment by prckent** [comment]
Thanks. That is a fair start. We'll have to tackle NEXUS and its python dependencies at some point: nexus/library and nexus/executables need to be installed. In use, the former needs to go on PYTHONPATH, the latter on PATH.

We'll add this to the to do list for upcoming releases since as you point out all systems will have the same questions.

**Comment by yurivict** [comment]
While here, could you also add to the TODO list the item to be able to build the python binding alone, so that it will be possible to install it multiple times for various python versions? The best way is to have the python binding as a separate project, or otherwise to make sure that there is the cmake options combination that would build the python binding alone.

**Comment by markdewing** [comment]
There is no 'python binding' in the usual sense of the phrase.
The executables in nexus/executables are utility executables that happened to be written in python.  They are python 2 currently.    To make them universally available, we should convert them to work with python 3.
The nexus/library code is only compatible with python 2 at the moment.  It is independent enough of qmcpack that allowing a separate install would be a good idea.

**Comment by yurivict** [comment]
Ok, thanks for the explanation.

**Comment by prckent** [comment]
(I believe this is completed and will close the issue. If there are extra requests for the installer please make a new issue - we are keen to have feedback. The python 3 transition discussed above will have to happen during the next months because of the sunset of python 2 support in key libraries.)
