### ISSUE TITLE
128 atom NiO performance test fails intermittently

### ISSUE THREAD

**Issue by jtkrogel** [QMCPACK/qmcpack#1064]
The 128 atom NiO performance test fails intermittently, but should pass everywhere (bug).

**Comment by prckent** [comment]
Volta tests are working again after a reboot of oxygen.  https://cdash.qmcpack.org/CDash/testDetails.php?test=3147486&build=28233  . The previous weeks of failures occurred because the specified card ID was not found. The hint for this is the failing _Z14get_device_numv in the errors e.g. https://cdash.qmcpack.org/CDash/testDetails.php?test=3116366&build=28107 

<img width="791" alt="image" src="https://user-images.githubusercontent.com/13683814/45434391-53a01480-b67c-11e8-835c-661b7dda8e74.png">

**Comment by ye-luo** [comment]
The error "Signal code: Integer divide-by-zero" shows a error trap is needed if no device is found.

**Comment by ye-luo** [comment]
This is fully cured.
I changed the timeout limit on bora to 800 seconds. This will be PRed soon with other needed changes for test automation.
@prckent brought the Volta card online.
