### ISSUE TITLE
Need to reduce the number duplicated files in performance test

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#1111]
The current performance tests have three sets, CPU, CPU with J3 and GPU.
The same test case in the three sets is largely identical. The only difference is
J123 replaced J12 in the CPU with J3 case.
The number of walkers in the input is increased from 1 to 32 in the GPU case.
In the near future the number of sets will increase because I will introduce the set for delayed update and batched algorithm in NLPP.
In order to reduce the maintenance pain, I'd like to keep only the CPU set and then use a script to generate all the other sets.

For people don't run the performance test via the ctest. A simple bash script will be available to generate the input files for all the sets.

Any concerns?

**Comment by markdewing** [comment]
The decision on generation and storage of the input files can be split.
The input files can be generated and maintained via the script, but still stored in the repo for easy reuse by others.
Storing the input files for all the variations seems like too much, though.  We'll need to figure out the right set to store.

**Comment by ye-luo** [comment]
The current way of manually running the tests copies files from sample folder to one level up with submit_cpu_cetus.sh and submit_gpu_cooley.sh scripts. So the files in the sample folder are never used in a run directly. I even consider the submit_cpu_cetus.sh and submit_gpu_cooley.sh actually a bit difficult to run. In a better way, all the input files should be generated and then the users have all the freedom to run them.

**Comment by prckent** [comment]
Due to holidays I have had a few extra days to think about this, but still prefer @markdewing 's suggestion.

Rationale: we need to make the input files as accessible as possible and minimize the number of steps for non-expert users to find and use the files. e.g. We have had several requests for performance inputs from computer centers, and adding a step or making the files less discoverable is not desirable. Having a script to help maintenance and consistency *is* desirable, so lets have scripts to create the inputs but also keep the generated inputs in the repo. The files are tiny so we don't need to be concerned with the size of the git history.

The same considerations can be applied to any of our input files. Once we can specify "fixed total work" the need for variants will be reduced.
