### ISSUE TITLE
APP_ABORT no more effective

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#1246]
short-LiH_solid_1x1x1_pp-arb-vmc_hf_noj-1-16 on a real build.
The test run should be stopped by APP_ABORT complaining complex build is needed.
After the mpi wrapper change, APP_ABORT only prints the error without stopping the code.

**Comment by markdewing** [comment]
Two parts to the issue
 1. mpi3 wrapper set errors to return (MPI_ERRORS_RETURN)
 2. OOMPI calls Abort on OOMPI_COMM_WORLD, which is now not set up with the world communicator  and it calls MPI_Abort with a NULL communicator, which is an error and the function returns (as set in 1) rather than aborting.

I think the fix will be to call MPI_Abort  in APP_ABORT, so as to access MPI_COMM_WORLD directly. This is one of few (only?) places in MPI where you want to use MPI_COMM_WORLD directly.

To use the new wrapper, we will need to either keep a reference to 'world' or a reference to 'env', from which we can get 'world'.   For now it seems more straightforward to call MPI directly.

**Comment by jtkrogel** [comment]
Did APP_ABORT previously bring down all members of an ensemble run if only one member called it?

There are cases where we do want this behavior and others where we likely don't.

**Comment by markdewing** [comment]
I think the behavior is implementation-defined when MPI_Abort is called on some communicator other than  world.

**Comment by markdewing** [comment]
It looks like OOMPI initializes OOMPI_COMM_WORLD to the world communicator and I don't think it ever gets reassigned.  APP_ABORT calls abort on OOMPI_COMM_WORLD, so I think APP_ABORT always terminates the entire job.
