### ISSUE TITLE
qmca with python 3

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#1287]
With the python/3.7.0 module on Summit, I got the following error
```
$ qmca
  File "/ccs/home/yeluo/opt/qmcpack/nexus/bin/qmca", line 415
    exec 'obeys_rule='+rule
                     ^
SyntaxError: Missing parentheses in call to 'exec'
```

**Comment by prckent** [comment]
Summit has a python2 module. Does this work for you?

**Comment by markdewing** [comment]
Some of the Python 2 features in qmca are unused, as they are part of a generic infrastructure copied from the reset of Nexus.  The I think the infrastructure code has also drifted from that in the rest of Nexus (?).

The options in fixing qmca are
1. Update code to use Python 3 in qmca, but keep all the infrastructure (problem is this code is not used and has  no tests, so it's not clear if fixes would work)
2. Remove unused infrastructure code in qmca (would eliminate some of the Python 2/3 incompatibilities), but might make the infrastructure code out of sync with the rest of Nexus.
3. Update common infrastructure with Nexus to be Python 2/3 compatible, and incorporate that into qmca.

**Comment by prckent** [comment]
Provided the python 2 module works on Summit, there is simply no bug here, so I will change the issue type until @ye-luo  or someone else reports otherwise.  We should make our python 2 version dependency clear and listen for other python issues. 

Python 3 support and improving our handling of the python environment is definitely a worthwhile feature improvement. However there are other things that would have far higher return. e.g. Fixing the more important known tagged bugs that affect science ( e.g. #925 , #925 , #1054 ) or improving testing situation.

**Comment by prckent** [comment]
Did you ask OLCF to fix this? We are far from being the only python2 user.

**Comment by prckent** [comment]
I have reported this problem to OLCF. The problem is bigger than qmca and related to python2 and numpy usage in general. A solution is required to get NEXUS to work (@jtkrogel ). The current python2 and py-numpy/1.11.2-py2 modules were built requiring gcc/4.8.5 and set to conflict with gcc new enough to support C++14. It should be an easy fix for the Center.

**Comment by ye-luo** [comment]
@prckent Thanks. Based on the reply from OLCF,  python/2.7.15-anaconda2-5.3.0 is the current solution and it works for me.

**Comment by prckent** [comment]
Superseded by #1290 and #1293
