### ISSUE TITLE
Original MSD tests removed

### ISSUE THREAD

**Issue by jtkrogel** [QMCPACK/qmcpack#1309]
PR #1289 removed the original tests for the MSD code.  In general, I don't think we should remove old tests (unless they are no longer valid) since they were created with older versions of the code.  New features should result in tests being added, but not removed.  Additionally the removal creates more work generally (e.g. I just finished generating updated reference data for the old tests and the more tests we replace the more work of this type we create).

I am in favor of restoring the old tests:
```
short-C2_pp-msdj_vmc
short-C2_pp-msdj-traditional_vmc
long-C2_pp-msdj_vmc
long-C2_pp-msdj-traditional_vmc
```
while keeping at least the H5 tests introduced in #1289. I am ambivalent as to whether we keep the new XML ones as they overlap with the old tests.

@prckent @anbenali @ye-luo thoughts?

**Comment by anbenali** [comment]
There is a reason why previous test was removed.
QP now can generate an HDF5 in the format directly read by qmcpack.
However、 when selecting the determinants、 there is a portion of stochastic
behaviour leading to some determinants being selected at different
iterations. When generating the new H5 files from QP、 the number of
determinants was different than the original test. Not by much but still.
Since the point is to keep the same statistics between full hdf5 and xml I
had to update the reference xml otherwise we would have ended with 2 xml
tests for the same case.

The C2_pp test as is now is coherent but reinstating the old one would mean
creating a new test since the statistics will be different.

Other than this specific case、 I agree with you that the tests should never
be modified unless impossible to do otherwise..

**Comment by jtkrogel** [comment]
As I understand, the purpose of the test is to see if QMCPACK behaves the same with the same inputs over time.  If a test is valid at the QMCPACK side, then it should not be removed IMHO.  Since the change you mention is in Quantum Package/the wavefunction generation step, the old test is still valid.

**Comment by anbenali** [comment]
The old is still valid. It is not the issue. However it will be duplicated.
For testing it is valuable to have the same wavefunction in xml format and
hdf5.  Since we cannot generate an hdf5 test based on the old xml we will
end up with 2 tests (xml) testing the same thing. If you want to bring back
the old test and add it to the set I do not mind. I just do not see the
value of it. If you want to replace the new xml test with the old then I do
not agree as we will end up with different wavefunctions between hdf5 and
xml.
All in all this is not a strongly contentious point for me in the sense
that I only care about detecting errors when they happen. If someone wants
to remove a test/code I put and replace it with something better I am
happy. I gave the reasons why I removed the old tests and why I wanted the
new tests to have same WF between xml and hdf5 but any improvement is
welcome. If you want me to generate an all new test i can do that too.

**Comment by prckent** [comment]
Good discussion. Since we maintain and advertise the ability to use the XML format, we need a test of the old XML format. The easiest way to do this would be to restore the old test. If we don't want to support the old XML format any more -- and to be clear, I think we do -- we should completely remove the functionality.

Ideally we would be able to test the input system independently of the simulation, but this is not the case.

**Comment by prckent** [comment]
I misunderstood. I don't have a problem with the current situation then.  Good to have the tests the same.

**Comment by jtkrogel** [comment]
Very well.  Closing.
