### ISSUE TITLE
Detect and protect C++ standard library version for non GNU compilers

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#1341]
It happened a few times that people try to use Intel with the most recent gnu standard library.
For example, Intel 18 with gnu 7 or 8.
Due to the fact that Intel 18 supports C++14 not C++17 while newer standard library uses newer language features, the compilation aborts with error.
We need to find a way to catch this scenario in CMake. Currently we only check the lower bound.

**Comment by prckent** [comment]
Any ideas for how to catch this? It would be a nice feature. Does the GNU standard library declare its version via defines? Checking the available gcc would not be a good proxy.

Ideally Intel themselves would catch this problem since it must be a common error.

**Comment by prckent** [comment]
A 99.9% effective solution would be a check as part of our Intel compiler config. Good enough for us.

**Comment by prckent** [comment]
1. Capture one of the failures, say where Intel2018.3 fails with too recent GNU library.
2. Make the smallest possible reproducer, and add a test compile of this feature that is prone to failure.
3. If the compile fails print an error "Standard library feature XXX failed a compile check. This can be due to use of too recent standard library for your selected compiler. See the documentation for guidance."

This isn't really any different from our current library check.

**Comment by prckent** [comment]
I suggest we reevaluate the situation whenever the next update of Intel2019 is out. Based on their historical record, this should be only a few months.

**Comment by ye-luo** [comment]
The issue of too new standard library from gnu when using Intel 18 was caused by some place inside the unit test framework catch.hpp. @markdewing what is the C++ standard used by catch?

**Comment by markdewing** [comment]
C++11 is used by Catch2. I don't know if it internally detects various
features.
