### ISSUE TITLE
Raise boost minimum version

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#1616]
Current minimum is 1.61 which is 3 years old. It is time to raise the version.
Any preference?

On the other hand, I was thinking how to support boost version.
libboost is 1.70 now. So 3 releases per year.
Do we need to support all versions? Can we pick one release per year and make sure it works?
We list these versions to users. For intermediate version, it is on your own.
With a two year rule, we only need to support 2 versions in total.
Any thoughts?

**Comment by prckent** [comment]
The two year "rule" we have discussed for compilers would indicate v1.64.0 as the oldest to support
https://www.boost.org/users/history/

Now that we have the deterministic tests, working through different combinations is relatively quick.

**Comment by prckent** [comment]
Is there any functionality in a newer Boost that you would like to use?

The "two year rule" means we could bump the version, but there is no need to be disruptive unless we have good reasons.

**Comment by ye-luo** [comment]
@prckent The question was raised because you put 1.65 on oxygen. Then you put back 1.61 and it works fine. So it is not critical to raise the version number. I prefer staying with 1.61. It is your call.

**Comment by prckent** [comment]
I think that this can be closed. We are now following the two year rule https://github.com/QMCPACK/qmcpack#prerequisites . Oxygen is testing Boost 1.70.0 and 1.61.0. These versions can be bumped for specific feature support at any time, but generally I envisage updating the versions we test against around the time of a release (either for validation or, post-release, so that we can use new features in develop). Since our usage of Boost has not changed I kept 1.61.0, but 1.65.0 is currently at the two year boundary.
