### ISSUE TITLE
Cusp correction crashes

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#1623]
See e.g. https://cdash.qmcpack.org/CDash/testDetails.php?test=5233020&build=60682 
These are Intel2018 release builds. short-chn_ae_cuspCorrection-vmc-1-16 is crashing somewhere in the initial VMC. A PR from last week is likely at fault since the runs appeared stable before.

<img width="802" alt="image" src="https://user-images.githubusercontent.com/13683814/58766803-fec96480-8550-11e9-96ae-643ab6dfbb3b.png">

**Comment by ye-luo** [comment]
This was triggered by my change of removing VLA.
After looking at the code, I found a deep issue in how the code is handling thread private copies in lcao. I think it is good case study and demonstration how to use smart pointers instead of manage pointers ourselves. Later, we propagate the new way throughout the code. Before a clean fix is provided, I will fix this bug by defining variables local to the function. This will be slow but working correctly.

**Comment by prckent** [comment]
Do valgrind or msan catch this bug in a useful way?

**Comment by ye-luo** [comment]
Every thread owns a pointer to a data structure A which contains a vector B. Every thread tries to resize B via the pointer and caused a data race. The real issue is not the race but every thread should own a copy of A instead of sharing a pointer to A.

1. ThreadSanitizer is a tool that detects data races.
2. MemorySanitizer (MSan) is a detector of uninitialized memory reads in C/C++ programs.
3. AddressSanitizer is a fast memory error detector.

I think it is 1 and 3 should tell us something but probably not 2.

**Comment by prckent** [comment]
If a long term fix will take a while,  a short term fix is desirable so we can make a post-workshop release.
