### ISSUE TITLE
Prefer `throw std::runtime_error` to `APP_ABORT macro`

### ISSUE THREAD

**Issue by PDoakORNL** [QMCPACK/qmcpack#1803]
This gives us a path to better error handling wrt non-trivial concurrency and it can be checked for in catch test program.

Example
```C++
REQUIRE_THROWS_WITH(test_block(nested_tasks, std::ref(count)),
                      Catch::Contains("TasksOneToOne should not be used for nested openmp threading"));
```

On the other hand we do want to call MPI_Abort eventually. Although it doesn't appear this happens for unhandled exceptions right now.

**Comment by ye-luo** [comment]
Could you move this to #125? Just to reduce scattered issues.

**Comment by prckent** [comment]
Can this route to used to definitely bring down a parallel MPI program? The risk is that we stop one MPI task but leaving N-1 running. This is not acceptable behavior for a production code due to the potential for massive HPC time wastage. I would prefer that we use exceptions for many reasons but they have to work in real-world production.

**Comment by markdewing** [comment]
I've had trouble with C++ exceptions in MPI programs - I think it was debugging some of the cusp condition problems.   It may be a BG/Q issue, but it's worth checking on other platforms.
