### ISSUE TITLE
MKL in non-Intel compilers

### ISSUE THREAD

**Issue by mmorale3** [QMCPACK/qmcpack#184]
I can't get cmake to find the correct mkl blas/lapack libraries.
I set "MKL_HOME" as described in the README, but cmake still 
finds the generic lapack/blas libraries from /usr/lib64.
Building with gnu compilers.

**Comment by mmorale3** [comment]
There seems to be no real support for this on the cmake tree, am I wrong?

**Comment by ye-luo** [comment]
I don't think MKL_HOME is effective.
Which compiler were you using?

**Comment by markdewing** [comment]
I use

-DBLA_VENDOR=Intel10_64lp_seq -DCMAKE_PREFIX_PATH=$MKLROOT/lib

to use MKL with gcc and clang.

**Comment by mmorale3** [comment]
I'm using gcc. I'll try Mark's suggestions. This should be added to the README somewhere.

**Comment by ye-luo** [comment]
Agree. We need a section in the manual to describe this recipe and add a reference in the README.
Just to be sure that the corresponding script under your MKL installation mkl/bin is sourced. Then $MKLROOT is defined.

**Comment by mmorale3** [comment]
Well, I'm back to toolchains. Can't get this working on LLNL.

**Comment by ye-luo** [comment]
Sigh. Could you provide a bit more info? We can investigate why it didn't work.
1, Did you source the script provided by MKL?
2, Could you echo $LD_LIBRARY_PATH and $MKLROOT
3, Your exact cmake command line.
4,  The cmake output.

**Comment by ye-luo** [comment]
Keep this issue alive until the manual/readme is updated.

**Comment by prckent** [comment]
We build with gcc and MKL in the nightlies. The script for this with example configure lines is tests/test_automation/nightly_ornl_oxygen.sh . See the gcc_mkl settings. We use exactly Mark's line and Ye's sourcing to define MKLROOT.

source /opt/intel2017/mkl/bin/mklvars.sh intel64
and
-DBLA_VENDOR=Intel10_64lp_seq -DCMAKE_PREFIX_PATH=$MKLROOT/lib

Since LLNL orginated SPACK, this should be fixable. Please update with the issues.

**Comment by prckent** [comment]
Closed by #255
