### ISSUE TITLE
2D QMCPACK does not build

### ISSUE THREAD

**Issue by rcclay** [QMCPACK/qmcpack#188]
Did not thoroughly test, but initial attempts to compile with OHMMS_DIM=2 fail.  This worked as late as 2013 with the 2D HEG.

**Comment by prckent** [comment]
This would be nice to have working. Do you have a previously working 2D HEG example that can be used to help debug? Presumably there is some minor C++ breakage.

**Comment by prckent** [comment]
Confirming that the build fails with -DOHMMS_DIM=2

The first error:

> [  6%] Building CXX object src/CMakeFiles/qmcbase.dir/Particle/ParticleSet.cpp.o
git_QMCPACK_qmcpack/qmcpack/src/Lattice/CrystalLattice.h(239): error: no instance of overloaded function "qmcplusplus::CheckBoxConds<T, 2U>::inside [with T=double]" matches the argument list
            argument types are: (const qmcplusplus::TinyVector<double, 2U>, const qmcplusplus::TinyVector<int, 2U>)
      return CheckBoxConds<T,D>::inside(u,BoxBConds);
             ^
git_QMCPACK_qmcpack/qmcpack/src/Lattice/LatticeOperations.h(239): note: this candidate was rejected because arguments do not match
    inline static bool inside(const TinyVector<T,2>& u, TinyVector<T,2>& ubox)
                       ^
git_QMCPACK_qmcpack/qmcpack/src/Lattice/LatticeOperations.h(235): note: this candidate was rejected because mismatch in count of arguments
    inline static bool inside(const TinyVector<T,2>& u)
                       ^
          detected during instantiation of "bool qmcplusplus::CrystalLattice<T, D, ORTHO>::isValid(const qmcplusplus::TinyVector<T, D> &) const [with T=double, D=2U, ORTHO=false]" at line 543 of "git_QMCPACK_qmcpack/qmcpack/src/Particle/ParticleSet.cpp"

There are also issues with RealType not being defined in TwoDEwaldHandler.h that cascade to other uses, possible problems in the molecular code, and certainly issues with the unit test codes that were never written with 2D in mind. On first glance this looks to be a Series of Small Breakages(TM).

**Comment by prckent** [comment]
Needing a separate build for 2D is a design bug. One alternative would be to enable 2D boundary conditions and Coulomb with the current "3D" code.

**Comment by prckent** [comment]
At the ECP planning meeting (LLNL, May 2018), we briefly discussed this issue. The conclusion at the time was that the 2D code could be removed. Anyone with a strong need for 2D should comment here. Support for e.g. graphene is handled via the 3D code with appropriately modified boundary conditions.

**Comment by prckent** [comment]
This feature should be removed from the code

**Comment by jtkrogel** [comment]
The "does not build" aspect is no longer an issue.
