### ISSUE TITLE
Status of backflow code is uncertain

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#200]
There are no tests or reference inputs for the backflow code. This was working a few years ago, but might not be working the production version, particularly with optimization.

First step is to find some inputs and assess functionality: does VMC work? optimization? are old runs reproducible?

**Comment by Paul-St-Young** [comment]
VMC with backflow works in the current version of the code. However, Backflow optimization is broken. Optimization errors out with:
Fatal Error. Aborting at Need specialization of SPOSetBase::evaluate_notranspose() for grad_grad_grad_logdet.

Backtrace shows that the `evaluate_notranspose()` call originated from the `EsinplineAdoptor` class. The `EinsplineSetExtended` class has the needed specialization of `evaluate_notranspose()`. @ye-luo pointed out to me that the switch from `EinspleinSetExtended` class happened at svn revision 6465 or git commit ef857a4a96ac25202bf941aeb87a1a4763cca98e on May 25 2015.

I was able to verify that backflow optimization works in svn revision 6296. Using the optimized backflow, I ran VMC with both rev6296 and the current github develop branch and got the same total energies and variances. I used bcc hydrogen with 54 atoms as a test system, which may be a bit big for a regular test.

The current way the `BackflowTransform` class handles the optimizable parameters is rather sketchy. Instead of using `opt_variables_type myVars;` to map from local to global index, it uses a locally constructed map `optIndexMap`.

In order to restore a reliable backflow implementation, there are at least two things to do:

1. Implement `evaluate_notranspose()` for grad_grad_grad_logdet in `EinspleinAdoptor` class.
2. Revamped the optimization parameter mapping in `BackflowTransform` class.

**Comment by prckent** [comment]
Thanks. Good to hear that VMC reproduces old runs. Almost certainly then, it is only the area of optimization that needs revision.

The assumptions of the old optimization parameter mapping certainly need fixing or verifying. I believe (mentioned by @mmorale3 ) it assumes the backflow parameters  are first.

**Comment by ye-luo** [comment]
Settled by #1204 #1225
