### ISSUE TITLE
Testing: Status of all-particle move QMC methods not clear; tests needed

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#229]
QMCPACK supports all-particle move based algorithms as well as the conventional particle-by-particle algorithms. The state of these is unclear as identified by #227 . VMC all electron is now working.

- Which DMC algorithms work?
- Is there pseudopotential support?

A first step would be to try all particle move versions of the current tests. For unimplemented methods we should add error traps and update the manual. e.g. GPU support.

**Comment by rcclay** [comment]
I briefly checked the VMCUpdateAll w/ and w/o drift a few weeks ago, and found them to be operational and consistent with the pbyp numbers.  Did PR #227 turn up any numerical issues when using electrons?

**Comment by prckent** [comment]
@rcclay Please do

**Comment by rcclay** [comment]
Preliminary tests are in.  I considered the 1x1x1 Diamond example used in the ctest runs.  512 walkers, time step of 0.005 Ha^-1.  Still trying to beat down error bars on my workstation, but:
1.)  DMC Alle driver w/ pseudopotentials and w/o T-moves is good.  Agrees with PbyP for every observable.
2.)  DMC Alle driver w/ pseudopotentials and w/ T-moves is uncertain.  Total energy agrees with PbyP, but all other quantities are off.  Example with the potential energy:  PbyP says <V>=-22.0265(19), but Alle says <V>=-22.0584(42) (Alle is still running, hence the larger error bar).  Either way, right now it's a 6 sigma difference between the two.  The reason I say the status of this driver is uncertain is because I haven't ruled out that it might be a timestep error.

**Comment by rcclay** [comment]
Update:
2.)  DMC Alle driver w/ pseudopotentials and w/ T-moves seems to work, however, the timestep error is large.  Specifically, I ran all electron calculations at t=0.005, 0.0025, and 0.001.  Performing a linear time step extrapolation, I find the all electron results estimate <V>=-22.021(4), which is within error bars of the pbyp estimate.  Discrepancies in all other observables likewise vanish.

Can't tell if the large timestep error is a bug or a feature.  Whatever it is, the DMC Alle driver (with T-moves) gives the correct results in the tau->0 limit.  Perhaps its use should be discouraged unless there is a compelling reason to do otherwise.

**Comment by prckent** [comment]
Current status: VMC and DMC all electron tests for bccH now included. PP tests still required.

**Comment by ye-luo** [comment]
@rcclay What system exactly were you using?
Diamond 1x1x1 has DMC energy -10.531583 Ha, 2x1x1 has DMC energy at -21.844975 Ha in recorded in the tests/system/CMakeLists.txt

**Comment by rcclay** [comment]
The quoted numbers were for the LocalPotential, since this is usually much more susceptible to time step error than the total energy.

**Comment by rcclay** [comment]
Same 1x1x1 diamond test system as in the ctest.

**Comment by ye-luo** [comment]
Everything seems correct.
```
pbyp-ref-yes  -10.528636 +/- 0.000187  -22.028660 +/- 0.001759
pbyp-aos-yes  -10.528729 +/- 0.000180  -22.029836 +/- 0.001871
pbyp-soa-yes  -10.528531 +/- 0.000196  -22.026540 +/- 0.001685

pbyp-ref-no  -10.531438 +/- 0.000167  -22.017884 +/- 0.001983
pbyp-aos-no  -10.531374 +/- 0.000183  -22.015919 +/- 0.001876
pbyp-soa-no  -10.531207 +/- 0.000159  -22.017363 +/- 0.001894

alle-ref-yes  -10.528451 +/- 0.000160  -22.052206 +/- 0.002072
alle-aos-yes  -10.528219 +/- 0.000170  -22.051495 +/- 0.001816
alle-soa-yes  -10.528316 +/- 0.000154  -22.051366 +/- 0.002052

alle-ref-no  -10.530877 +/- 0.000172  -22.013966 +/- 0.002043
alle-aos-no  -10.530937 +/- 0.000164  -22.008233 +/- 0.001839
alle-soa-no  -10.531159 +/- 0.000170  -22.013118 +/- 0.001746
```

**Comment by jtkrogel** [comment]
pbyp and alle are clearly different in potential energy:

    pbyp-*-yes ~ -10.5286(2)  -22.028(2)
    alle-*-yes ~ -10.5283(2)  -22.051(2)    PE differs by 10 sigma

    pbyp-*-no  ~ -10.5314(2)  -22.017(2)
    alle-*-no  ~ -10.5309(2)  -22.013(2)    E differs by 3 sigma, PE differs by 2 sigma

Also, alle-aos-no looks suspect:
    
    alle-ref-no  -10.5309(2)  -22.014(2)
    alle-aos-no  -10.5309(2)  -22.008(2)  PE differs by 3 sigma

Are the pbyp/alle differences due to timestep?  The alle-aos-no differences must be something else.

**Comment by ye-luo** [comment]
```
pbyp-*-yes ~ -10.5286(2)  -22.028(2)
alle-*-yes ~ -10.5283(2)  -22.051(2)    PE differs by 10 sigma
```
pbyp and alle doesn't agree with Tmove=yes. See the original comment of Ray. I'm not changing this situation.
```
pbyp-*-no  ~ -10.5314(2)  -22.017(2)
alle-*-no  ~ -10.5309(2)  -22.013(2)    E differs by 3 sigma, PE differs by 2 sigma
```
I think this is acceptable and these four numbers are both from ref(v3.1.1). I think it is due to the underestimation of error bar in DMC. The results showed here are from my longer runs. I was worried about in the beginning seeing close to 3 sigma difference and performed 4X longer runs and the numbers are still within 3 sigma.
```
alle-ref-no  -10.5309(2)  -22.014(2)
alle-aos-no  -10.5309(2)  -22.008(2)  PE differs by 3 sigma
```
This is also from my longer runs. It can be just fluctuation. Trying a wider run now.

**Comment by ye-luo** [comment]
A wider run gives me
```
alle-aos-no-wide -10.531052 +/- 0.000116  -22.013470 +/- 0.001344
```
Seems like a statistical thing.

**Comment by jtkrogel** [comment]
By "wider" you mean more nodes and same number of blocks/steps?

**Comment by ye-luo** [comment]
2X walkers(nodes) and same number of blocks.

**Comment by ye-luo** [comment]
We have tests based on bccH and DiamondC.
I think we have VMC w/ and w/o drift and DMC covered.
DiamondC covers NLPP.
So we have all cases covered and one remaining issue #766 is tracked separately.
