### ISSUE TITLE
SOECPotential compiler warnings and incorrect copyright + authors

### ISSUE THREAD

**Issue by PDoakORNL** [QMCPACK/qmcpack#2350]
**Describe the bug**
Following @ye-luo 's example we should use the `override` keyword when overriding a defined (i.e. not) `virtual ReturnType foo(...) = 0;` member function. 

**To Reproduce**
1. build develop with llvm
2. cmake command
3. full program/test invocation command
4. Take a look at file.

**Expected behavior**
No compiler Warnings

**System:**
 - system name [e.g. fusiont5, summit]
 - modules loaded [e.g. output of `module list`]
 - other systems where this is reproducible [e.g. "my laptop", "none"]

**Additional context**

**Comment by camelto2** [comment]
I believe PR #2343 addresses all of the compiler warnings coming from SOECPotential. I add to that PR the copyright/author stuff

**Comment by camelto2** [comment]
Maybe I can ask here since I don't see it documented anywhere or I've overlooked it.

Is the copyright year supposed to be updated every time a file is edited? Or does it stay as the year that the file was initially created? 

There are other files that were create in relation to the SOECPotential, like SOECPComponent.h and SOECPComponent.cpp which were created in 2019 by Ray and developed by him and me, but the copyright/author/developer list is clearly wrong. I'll update those accordingly as well

**Comment by ye-luo** [comment]
The year should be consistent with the date when a file was touched for the last time.

**Comment by camelto2** [comment]
ok. if that is the case then a number of them need to be updated to reflect some of the previous PRs for SO stuff. I'll update those and commit again

**Comment by prckent** [comment]
Good question Cody. For the spin orbit files that you are touching use the latest date as Ye stated above. For the developer list in all the SO files, please update them to make them correct to your knowledge. Since these are all recent files there should be few questions.

Commenting more broadly, we will need to take some advice on updating the headers and look at what some other large projects are doing. Many of the files have a generic list that is clearly generous, or that has not been updated. The git history could be used as source of truth.

**Comment by camelto2** [comment]
Closed by #2343
