### ISSUE TITLE
Large breakage in CUDA code and deterministic tests

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#2390]
**Describe the bug**

100+ deterministic tests are failing for cuda complex, real, and full precision builds.

Deviations from expected values are sizable. e.g. 2 million sigma for diamond 2x1x1 https://cdash.qmcpack.org/CDash/testDetails.php?test=7938301&build=112564

Yesterday's https://github.com/QMCPACK/qmcpack/pull/2382 was checked, so most likely another PR caused a problem.

**To Reproduce**
1. release version or git commit hash being built
2. cmake command
3. full program/test invocation command
4. additional steps

Run the deterministic tests from the latest develop for any CUDA version.

**Expected behavior**

Tests should pass

**System:**
 - system name [e.g. fusiont5, summit]
 - modules loaded [e.g. output of `module list`]
 - other systems where this is reproducible [e.g. "my laptop", "none"]

nitrogen, standard nightly build configuration.

**Additional context**

**Comment by ye-luo** [comment]
This is caused by #2385.

Here is how RNGs are initialized and used in QMCPACK.
1. before initialization.
QMCPACK creates one global RNG and Nthread children RNG.
2. During initialization, constructing all the objects.
Only global RNG is used.
3. During QMC methods VMC/DMC.
CPU code uses per thread RNG, GPU uses global RNG.

Extra initialization consumes global RNG and alter the trajectory of later VMC/DMC on GPU but not CPU.

**Comment by ye-luo** [comment]
A simple fix is to put
```
#if !define(QMC_CUDA)
#endif
```
around. Is this an acceptable fix?

**Comment by prckent** [comment]
I think yes, but also put a hard abort on QMC_CUDA in the spin-orbit code, if there is not one already.

**Comment by camelto2** [comment]
If I understand the issue as Ye laid out above, it is due to the random initialization of the spin variables. this was needed to fix a bug I was seeing in VMC with drift.  Since we don't support GPU currently for spin stuff, I will just guard the spin initialization with the ifndef QMC_CUDA.

**Comment by ye-luo** [comment]
@camelto2 I'm working on the fix with the guard of spin calculation with CUDA.

**Comment by camelto2** [comment]
oh ok. I may be wrong, but I think the only issue is in the particle set stuff I added in PR #2385  to randomize the spins. For the QMC, that should already taken care of by the QMCFactories.

 For example, in VMC if cuda is defined you use VMCcuda in VMCFactory and VMC otherwise. The only place where dynamic spin calculations are utilized in the the VMC.cpp, and sets the movers as SOVMCUpdatePbyP if you ask for SpinMoves. That doesn't happen in the CUDA version...so I think the drivers should be ok.

**Comment by ye-luo** [comment]
@camelto2 If someone runs legacy cuda with input tag `SpinMoves="yes"` we don't want the run going through silently. I added a guard to stop the run.
