### ISSUE TITLE
Complex gaussian test is failing

### ISSUE THREAD

**Issue by jtkrogel** [QMCPACK/qmcpack#2566]
short-diamondC_1x1x1_pp-vmc_gaussian_sdj-1-16 fails when run in complex.  See

https://cdash.qmcpack.org/CDash/testDetails.php?test=8838131&build=125922

The failure is:
```
Fatal Error. Aborting at LCAOrbitalBuilder::readRealMatrixFromH5 Missing /Super_Twist/eigenset_0_imag from HDF5 File.
```

Presumably the test is meant to be run only with the real code and a guard is needed.  Correct @anbenali?

**Comment by prckent** [comment]
Indeed all complex runs of this test are failing https://cdash.qmcpack.org/CDash/testSummary.php?project=1&name=short-diamondC_1x1x1_pp-vmc_gaussian_sdj-1-16&date=2020-07-01

**Comment by prckent** [comment]
@anbenali 

Is this a recent breakage or do we need to add an unsupported note + abort to the code? My guess is that a file/file format has not been updated properly, or a type is bad etc.

https://cdash.qmcpack.org/CDash/testSummary.php?project=1&name=short-diamondC_1x1x1_pp-vmc_gaussian_sdj-1-16&date=2020-07-30

**Comment by anbenali** [comment]
argh.. yes this is something that was ought to happen but I forgot to apply the correct fix. 

Originally all orbitals were stored per kpts. and named KPTS0/eigenstate_0 ... but then it became clear that we would store them in Super_twist instead. Since molecules and solids in the real code use the same path, I added retro-compatibility to make sure that we don't touch the tests and that we don't break old runs. But for the solids, since I was the only one using it when pushed the format I put the references with KPTS0 and did not add the back compatibility. The references need to be updated. 
I will do that now.

**Comment by anbenali** [comment]
fixed with an if statement. Forgot that I had added backward compatibility everywhere but must have acted too fast and forgot the case where people would run real WF with complex code. If needed we could add a warning that they should not..
