### ISSUE TITLE
How to set PWSCF starting_magnetization in Nexus?

### ISSUE THREAD

**Issue by gokaran** [QMCPACK/qmcpack#2805]
Dear Dr  Jaron Krogel,

I wanted  to simulate 2d  ferromagnetic materials like Fe3GeTe2  using QMC.  I  have included starting_magnetization=0.5  in scf and  in nscf section in Nexus input file. But  it give syntax error that expression cannot  contain assignment (this is coming from python i guess) .  I tried to test it with standard LiH  input file that come with  nexus example. The same problem arises.  However, this problem  is not arises if  system is homogeneous, say for example like graphene where all atom in simulations cell   are carbons only. How can I  able to  set start magnetization  in  our system using standard QE flag  like starting_magnetization or tot_magnetization ?  

Many  thanks in advance
Yours
Gokaran Shukla

**Comment by jtkrogel** [comment]
Copying your syntax error here:

```
SyntaxError: expression cannot contain assignment, perhaps you meant "=="? File "/opt/qmcpack-3.7.0/nexus/examples/qmcpack/LiH/LiH.py", line 70 starting_magnetization(1)=0.5,
```

**Comment by jtkrogel** [comment]
The manifesting error you are facing is due to Python syntax.  Only whole names can appear in the input blocks, so `starting_magnetization(1)=0.5,` is invalid.

You should be able to achieve what you want this way, using a Python dictionary:

```
scf = generate_pwscf(
    starting_magnetization = {1:0.5}, 
    ...
    )
```

Note that Nexus alphabetizes the elements.  You may therefore prefer to specify the magnetic species by name, e.g.:
```
scf = generate_pwscf(
    starting_magnetization = {'Fe':0.5}, 
    ...
    )
```

You might find the information at https://github.com/QMCPACK/nexus_training/tree/master/monthly_meetings/03_190118_pwscf_input helpful.  Especially look at slide 10 of `Nexus_Monthly_Jan_2019.pdf`.

**Comment by gokaran** [comment]
Dear Dr Jaron Krogel,

Thank you very much for your kind  reply and this indispensable  help. Now its working .  Now, I learned  how to turn on various flag  like Hubbard_u  and all that in Nexus.  


Thanks a million

Yours
Gokaran Shukla
