### ISSUE TITLE
Add new machine to Nexus

### ISSUE THREAD

**Issue by zoowe** [QMCPACK/qmcpack#302]
I don't know for sure how formally this can be done beside modifying machines.py (add new class). If this is the only way, this has to be redone every time we update the code with new release.

Is it a better idea if information of local machine is stored in, say, ~/.nexus/local.py? machines.py loads it, if it exists? This can be done with few simple lines of code.

**Comment by jtkrogel** [comment]
Adding a new class to machines.py is the typical way of doing this (+commit/pull request).  I generally prefer this approach because the new machine will be available to all users from that point forward.

If you send along your modified machines.py, we can commit the relevant changes into the code.

**Comment by zoowe** [comment]
You are right about wildly available machines. For local machines (available to few users), I don't think it is worth to add to the package. I will make a pull request, anyway.

**Comment by jtkrogel** [comment]
OK, I see your point with small/local use machines.  I'm fine with checking for a local file and loading in machine definitions if present.  Do you mind using ~/.nexus/local_machines.py instead of ~/.nexus/local.py?  This seems like a useful feature overall.

**Comment by zoowe** [comment]
Perfectly fine.
