### ISSUE TITLE
Memory leak from OneDimGridFunctor.h

### ISSUE THREAD

**Issue by ddinge** [QMCPACK/qmcpack#3180]
The following tests seem to give a memory leak inOneDimGridFunctor.h according to otpt from DDT. Does anyone have any insight into the cause of the leak?

[short-C2_pp_msdj-H5-vmc-1-16_C2_pp_leak-report logbook.pdf](https://github.com/QMCPACK/qmcpack/files/6481566/short-C2_pp_msdj-H5-vmc-1-16_C2_pp_leak-report.logbook.pdf)

vmc_hf_sdj_hdf5

vmc_short_pp_msd_no_precompute_jas-H5

vmc_short_pp_msdj-XML-traditional

vmc_short_pp_msdj-XML

vmc_hf_sdj_xml

vmc_hf_sdj_edens_vor_short

vmc_short_pp_msdj-H5

**Comment by prckent** [comment]
There are lots of small leaks which is why we aren't running msan in CI (yet). 

I think these tests are for Gaussian basis wavefunctions. This code has had far fewer eyes on it than the more-used spline code. Generally the original authors weren't thinking through lifetime and ownership issues consistently. Good news is that these problems tend to be easy to fix.

AFAIK no one has looked at cleaning this code yet so your contribution to cleaning is very welcome.

**Comment by ye-luo** [comment]
Those leaks are from LCAO basis sets. Classes are not written RAII and caused leaks.
