### ISSUE TITLE
ctest PASS_REGULAR_EXPRESSION hide failure

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#3200]
**Describe the bug**
https://github.com/QMCPACK/qmcpack/pull/2991/files#r587881059
Adding PASS_REGULAR_EXPRESSION skips checking return code.

**To Reproduce**
build with -DENABLE_SANITIZER=asan
ctest -R deterministic-diamondC_1x1x1_pp-param-grad-1-1
I got pass but it should be marked as failure.

**Comment by prckent** [comment]
Hmm. Can you confirm your asan build fails this test with the PASS_REGULAR_EXPRESSION removed? Is there an intermediate script in the way that loses the failure exit code? This has been problem with other tests where some_script.py ignores/forgets a failure error code from the QMCPACK execution.

From the cmake docs https://cmake.org/cmake/help/latest/manual/cmake-properties.7.html#properties-on-tests this is not the expected behavior.

**Comment by ye-luo** [comment]
> Can you confirm your asan build fails this test with the PASS_REGULAR_EXPRESSION removed?
I tried and failure can be restored.

**Comment by prckent** [comment]
The supported way to handle more general checks is to write an additional wrapper to handle error codes, expected output etc.

#3202 adds a fail regexp which works for the sanitizers we are currently using. If we end up with very complex regexp we can write a wrapper, but for now I think we should keep things simple and just use the fail regexp to catch these additional errors.
