### ISSUE TITLE
Clang compilation not working because of -lomp option

### ISSUE THREAD

**Issue by correaa** [QMCPACK/qmcpack#3339]
**Describe the bug**

clang compilation not working, failing with

```
  /usr/bin/ld: cannot find -lomp
```

https://gitlab.com/correaa/boost-multi/-/jobs/1472222321#L888

**To Reproduce**

```
$ git clone https://github.com/QMCPACK/qmcpack.git
Cloning into 'qmcpack'...
Updating files: 100% (7019/7019), done.
$ cd qmcpack
$ export OMPI_CC=clang
$ export OMPI_CXX=clang++
$ mpirun --version
mpirun (Open MPI) 4.1.0
Report bugs to http://www.open-mpi.org/community/help/
$ mkdir build.noupdate && cd build.noupdate
$ cmake -DCMAKE_C_COMPILER=mpicc -DCMAKE_CXX_COMPILER=mpicxx -DBUILD_AFQMC=1 -DQMC_MIXED_PRECISION=1 -DCMAKE_BUILD_TYPE=Debug -DMPIEXEC_PREFLAGS="--allow-run-as-root;--bind-to;none" ..
-- The C compiler identification is Clang 11.0.1
-- The CXX compiler identification is Clang 11.0.1
```

https://gitlab.com/correaa/boost-multi/-/jobs/1472222321#L836

**Expected behavior**

I think `-lomp` should not be hardcoded in CMakeList

**System:**
 - Debian testing gitlab CI
 
https://gitlab.com/correaa/boost-multi/-/jobs/1472222321#L6

**Comment by ye-luo** [comment]
We never hard-code `-lomp` your Clang installation is missing openmp runtime library.

**Comment by correaa** [comment]
I see, so `-fopenmp` implies `-lomp`, solved it by installing LLVM OpenMP runtime `apt-get libomp-dev`.

It would be nice if CMake detected the libomp first. Not sure how to do it. https://cmake.org/cmake/help/latest/module/FindOpenMP.html

**Comment by prckent** [comment]
CMake was correct here - it tried to compile some source with omp and failed https://github.com/Kitware/CMake/blob/master/Modules/FindOpenMP.cmake#L150 . The problem is that the apt-installed compiler and runtime have  what anyone in HPC would consider standard  actually packaged as a optional/development feature. If common we could expand our error checking to be more informative. We already have helpers for various compiler weaknesses.
