### ISSUE TITLE
Documentation needed on creating SPO sets outside determinant

### ISSUE THREAD

**Issue by markdewing** [QMCPACK/qmcpack#3456]
The output usually includes this warning:
"WARNING !!!!!!! Deprecated input style: creating SPO set inside determinantset. Support for this usage will soon be removed. SPO sets should be built outside."

There needs to be some guidance in the manual on how to construct the new input style.  Especially how to convert the deprecated style to the new style.

Do any of the tests use the new style?

**Comment by prckent** [comment]
Yes. Considering that people also copy tests and use them as examples, nearly all the tests inputs should be updated as well to the modern format.

@anbenali Can this be done by hand? What would the updates look like?

As an aside, we have a similar problem with the old spline format, but it turns out that e.g. specifying all the atom positions would now be required, which is not possible to do with simple edits. Fortunately I think simple edits are all that is needed for the Gaussian SPOs. I spent some time looking at the spline case, but it would require coding some script to parse the old files and then update them suitably. This is a big problem imo, but it is what it is. Nexus is basically required to generate input in solids today. The pw2qmcpack converter doesn't write viable XML (unlike the molecular converter) or support supercells, so there is no quick route to generate solid state inputs.

**Comment by ye-luo** [comment]
Online doc has the new format https://qmcpack.readthedocs.io/en/develop/intro_wavefunction.html#
although "How to convert" we don't provide much help.

**Comment by ye-luo** [comment]
test_spo_collection_input_XXX are tests for the new style

**Comment by PDoakORNL** [comment]
MinimalWaveFunctionPool uses the new format now for its "input"

**Comment by markdewing** [comment]
One issue is the attributes on sposet_collection depend on the type attribute.   I think it be more sensible to move these out of the sposet_collection tag.  A few ideas:
1. Turn them into parameters
2. Use another tag - this could get rid of the `type` attribute altogether
3. Keep the type attribute and use another tag with a uniform tag name for the different types (`sposet` is already used,  but reuse it for this?)

Example of 1
```
 <sposet_collection type="MO">
     <parameter name="source">ion0</parameter>
     <parameter name="cuspCorrection">yes</parameter>
     <basisset>
       ...
    </basisset>
 <sposet_collection>
```

Example of 2
```
<sposet_collection>
   <molecularorbital source="ion0" cuspCorrection="yes">
         <basisset>
         ...
         </basisset>
   </molecularobital>
</sposet_collection>
```

Example of 3
```
<sposet_collection type="molecularorbital">
     <sposet source="ion0" cuspCorrection="yes">
     </sposet>
</sposet_collection>
```

**Comment by prckent** [comment]
Are there any complications with saving and loading of these parameters? We need a framework in which all of these parameters can potentially be optimized and saved/restored from disk.

**Comment by markdewing** [comment]
By "parameter" I don't mean "variational parameter".  I mean the "parameter" tag (as used in the drivers).

**Comment by markdewing** [comment]
Additional issue:  The `name` attribute does not seem to be used beyond printing it in the output.  If not present, it gets set to the `type` attribute value.

In general, it would be nice to have a convention for when something is being labeled or given an id for later reference, and when a name or id is being referenced.

**Comment by ye-luo** [comment]
The question is about how to handle SPOSet builder polymorphism.
type is keyword for selecting the derived type and I'd like to see it as an attribute of sposet_collection
The additional parameters as mentioned above "sources" "cuspCorrection", I agree the long list of attributes is unsatisfactory. I didn't touch this part due to no easy migration script ready to help users.
Depending on the nature of a parameter, if it is specific to a sposet, it should be place at sposet line or inside.
If it is global to all the sposets within a collection, it should be placed outside sposet.
In the example,  "cuspCorrection=yes" is usually determined by the basisiset and both basisset and cusp correction should be placed outside sposet since they are shared by sposets.
The current way
```
 <sposet_collection type="molecularorbital" source="ion0" cuspCorrection="yes">
     <basisset>
       ...
    </basisset>
    <sposet name="up" spin="0">
    <sposet name="dn" spin="1">
 <sposet_collection>
```
since we don't like long list of attributes, move them as parameters.

```
 <sposet_collection type="molecularorbital">
     <parameter name="source">ion0</parameter>
     <parameter name="cuspCorrection">yes</parameter>
     <basisset>
       ...
    </basisset>
    <sposet name="up" spin="0">
    <sposet name="dn" spin="1">
 <sposet_collection>
```
