### ISSUE TITLE
legacy CUDA implementation phasing out plan

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#3856]
As the batched drivers + OpenMP offload catches up in performance, we need to think about how to phasing out the legacy CUDA implementation. There is no exact timeline, phasing out the codes will be in stages.

Here is my proposal.
- [x]  delete WFOpt related legacy CUDA code. Would like to do this relatively soon as this slows down making better WFOpt drivers. #3984
- [x] delete VMC/DMC, namely all the result. This will depends on the need to keep the code and difficulty to keep the code around.

If you are using the GPU code but found `batched drivers + OpenMP offload` doesn't cover you need, please let us know. See https://github.com/QMCPACK/qmcpack/issues/3508

**Comment by williamfgc** [comment]
Not directly related to any feature in particular, but C++14 has a [deprecated attribute](https://en.cppreference.com/w/cpp/language/attributes/deprecated). Having it for any feature for a "reasonable" amount of time (depending on need) will give people enough time to be aware and adapt.

**Comment by prckent** [comment]
One consideration is that it is convenient to have the legacy CUDA implementation around since this is what the CORAL benchmark and therefore several machine acceptances rely on. If we remove the implementation completely from the latest version / development version then we might have to backport e.g. CMake and other fixes to an older released version. However we certainly don't need to keep the legacy CUDA optimizer paths around.

A trickier topic is our strategy for pushing/encouraging people to use the batched drivers and get sufficient feedback on them prior to dropping them or renaming the inputs etc.

**Comment by ye-luo** [comment]
Legacy CUDA has been removed from the code base https://github.com/QMCPACK/qmcpack/pull/4431
