### ISSUE TITLE
SkEstimator in h5 file is incorrect using all-particle move VMC

### ISSUE THREAD

**Issue by Paul-St-Young** [QMCPACK/qmcpack#419]
The SkEstimator values in hdf5 file are incorrect in VMC if all-particle move is used. The problem is virtually undetectable in all-particle DMC. I produced this problem using the current development branch (commit af960d3d6bde89956998d61d36ed4c9995a58e96) in the attachment. The results can be plotted using the included script "split_sk.py". The resultant plot is also attached here.

I tried playing with the calls `W.update()`, `H.auxHevaluate()` and `thisWalker.Age` in `VMCUpdateAllWithDrift::advanceWalkers` with no success. These are the only obvious differences compared to the all-particle DMC driver that I noticed.

Does anyone have an idea on why S(k) might be broken in VMC but not DMC?
Any suggestion is highly appreciated!

![broken-sk](https://user-images.githubusercontent.com/8060441/31642737-24d378b4-b2b2-11e7-9385-780aa42ca443.png)

[sk-wbyw-vmc.zip](https://github.com/QMCPACK/qmcpack/files/1389492/sk-wbyw-vmc.zip)

**Comment by jngkim** [comment]
It is how the exit condition is handled in wbyw not S(k).

S(k) is not stored and has to be computed.
Needs to rewrite update so that auxH stuff is called even though a move is
rejected. Just rearranging if conditions.

This is happening in DMC as well but not noticeable because of the
acceptance rate.

I proposed Ye to get rid of G in Walker but now I know why we have to keep
them.

You can communicate with me directly until the bug is fixed.
Jeongnim

**Comment by Paul-St-Young** [comment]
Hi Jeongnim,

Thanks for the explanation! Adding another `H.auxHevaluate` before `H.rejectedMove` seem to have resolved this problem. I am almost certain I tried this before. I probably put the fix in the wrong variant of advanceWalker ...

Thanks,
Paul

**Comment by jngkim** [comment]
You need to call P.update or something to compute S(k) with the old
position.

I will send you the proposed changes.

**Comment by jngkim** [comment]
This is just to give you an idea how to fix VMC wbyw.
Need to debug but this will show what I mean.

You should consider merging wbyw with/without drift. This can be done
nicely with lambda function.

Jeongnim
