### ISSUE TITLE
Update CI Clang to 15

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#4211]
**Is your feature request related to a problem? Please describe.**
Clang 15.0.0-rc3 addressed a few issues of Clang 14.
1. 14 has non-deterministic behaviors which caused bad code generation. Namely less reliable CI.
2. 15 now supports linking static archives with device code in it.

So need to update ORNL CI to use clang 15 and also remove USE_OBJECT_TARGET

**Comment by prckent** [comment]
@williamfgc Please include the full set of LLVM 15-rc3 tools in the installation. We'll want to try coverage builds, both regular CPU and offload to x86. i.e. llvm-cov needs to be available. Unless there is breakage in the rc, we should also switch to all the modern sanitizers since for sure there are worthwhile updates.

**Comment by ye-luo** [comment]
Right now offload to x86 is running on github action CI with clang 12. That can wait for clang 15 official release binaries if that makes an update easy.
