### ISSUE TITLE
Many tests fail (FreeBSD install of 3.15.0)

### ISSUE THREAD

**Issue by yurivict** [QMCPACK/qmcpack#4274]
**Describe the bug**
[qmcpack-test-failures.log](https://github.com/QMCPACK/qmcpack/files/9742029/qmcpack-test-failures.log)

**To Reproduce**
Build/test with ```BUILD_UNIT_TESTS=ON```.

**System:**
 - system name: FreeBSD 13.1 STABLE

**Additional context**
Version: 3.15.0 built from the FreeBSD port.

**Comment by prckent** [comment]
Yuri - If you have this build still setup please can you rerun a subset of the tests and report the summary here? We would like to see the output of `ctest -R deterministic`. From the looks of your logfile you have run nearly the entire test set. This includes stochastic tests that will fail from time to time. The deterministic (and unit, `ctest -R unit`) tests are the ones we guarantee to pass. These are also designed to be very quick to run and suitable for install checks. This in turn makes them sensitive to numerical changes e.g. if the Monte Carlo takes a different path due to "bad luck" Based on your logfile a few of the deterministic tests have failed, but not in a major way. It looks like we need to increase some numerical tolerances, that is all. By eye the stochastic test failures also looked reasonable, so happily I don't think there is a problem with the software or build in general. The underlying problems with stochastic tests is that they can't be made cheap, highly reliable, and informative all at the same time. Hence we made the deterministic set.

We can bump the test tolerances and make a new version. Thanks.

**Comment by prckent** [comment]
Yuri - FYI, we are gearing up for the 3.16.0 release. Installing FreeBSD in a test VM (first time), I was able to build the current development version and have all the relevant tests pass. i.e. `ctest -L deterministic` had zero failures.  The BUILD_UNIT_TESTS option that you used above is _not_ a QMCPACK CMake option, so it looks like the default full set of tests was run. Today this will always have lots of failures. Let us know if there is anything we should look at. Thanks.

**Comment by ye-luo** [comment]
Please open a new issue if there is remaining issues on FreeBSD.
