### ISSUE TITLE
Detection of XL compiler broken

### ISSUE THREAD

**Issue by atillack** [QMCPACK/qmcpack#434]
In some installations (SummitDev after an update) the XL compiler is not detected properly in CMakeLists.txt. CMake thinks the Clang compiler is installed - which then breaks our CXX_COMPILER_SUPPORT test.

Long story short: The fix is to add "OR ($ENV{CXX} MATCHES "xlC")" to the test in line 348 of CMakeLists.txt.

I can provide the diff tomorrow unless someone is quicker ;-)

**Comment by ye-luo** [comment]
Move my comments here. I think is a know issue of the most recent XL compiler that CMake thought it is Clang. I got this issue also on the miniQMC. IBM folks are looking at it. I think no need to fix our CMake.

**Comment by atillack** [comment]
@ye-luo I agree with you that this isn't necessarily our bug. At the same time, the fix is trivial enough and unlikely to cause trouble down the road (unless somebody else names their compiler xlC).

**Comment by prckent** [comment]
@atillack See the OLCF ticket [CCS #370333]  or talk to Matt Belhorn. Ye is correct.

The correct fix for the time being is to force cmake to use the XL compiler ID:

```
cmake -DCMAKE_C_COMPILER="mpixlc" \
     -DCMAKE_CXX_COMPILER="mpixlC" \
     -DCMAKE_C_COMPILER_ID='XL' \
     -DCMAKE_CXX_COMPILER_ID='XL' \
     -DBUILD_LMYENGINE_INTERFACE=0 \
     -DQMC_CUDA=1 \
     -DCUDA_ARCH="sm_60" \
     ..  
```

Eventually cmake and friends will be updated to recognize the IBM XL Clang-based compiler as XL. Indeed the updates last week broke the detection. The Summitdev build instructions need to be updated. However, there are other important problems: jsrun is somewhat buggy, and  task/thread placement is broken, making performance measurement suspect. See beta2 issues at https://www.olcf.ornl.gov/kb_articles/summitdev-quickstart/ . The LMYENGINE should now build due to #432 , but I have not checked it. Beta 3 needed!
