### ISSUE TITLE
QP2: Missing installation instructions for 'save_for_qmcpack'

### ISSUE THREAD

**Issue by vvp-nsk** [QMCPACK/qmcpack#4573]
Hi!

Could you please specify what version/branch of QP2 is supported? Could you please provide any instructions on how to get the 'save_for_qmcpack' plugin compiled and installed? 

Thank you in advance!

With best regards,
Victor

**Comment by prckent** [comment]
Hi Victor -

I have tagged Anouar who should know the current version and can add to manual or delegate appropriately.

When I last did this for the 2021 workshop https://github.com/QMCPACK/qmc_workshop_2021/blob/master/workshop_image/ubuntu_setup.sh#L105  I see that I used the latest git version at the time. Hopefully the QP related lines are still a good starting point. I can verify the exact version used if you would like since the workshop images are still available.

**Comment by vvp-nsk** [comment]
Hi  again!

I was trying to compile the one available at:

https://github.com/QuantumPackage/qmcpack

In fact, it is incompatible with neither QP2/stable nor QP2/dev-stable branches. To my understanding, the incompatibility problem comes from the PBC section of the plugin.  When it comes to previous few-years old version(s) of QP, it is very unlikely to get it compiled on modern HPC installations such as HPE CRAY XE. So, it would be great if someone just updates the manual and/or plugin source code. 

With best regards, 
Victor

**Comment by anbenali** [comment]
Hi Victor,

Please use the dev-pbc branch of the code since it is the one that we are
using.

Incidentally, once the plug-in is installed on the pbc-dev branch, it can
be called on an ezfio generated by the master branch.

Let me know if this stokes your issue

**Comment by vvp-nsk** [comment]
Hi again!

I just managed to compile the QP2/dev/pbc and 'save_for_qmcpack' plugin successfully.  Everything seems to work smoothly. 

Thank you!

With best regards, 
Victor
