### ISSUE TITLE
CPU GPU runtime comparison 

### ISSUE THREAD

**Issue by zohimchandani** [QMCPACK/qmcpack#4647]
Do you have any results for CPU and GPU runtime comparison for a given problem?

Thanks

**Comment by ye-luo** [comment]
What did you mean by "runtime comparison"?
For CPU, GPU comparison see https://arxiv.org/abs/2209.14487  figure 6.

**Comment by prckent** [comment]
I assume you are interested in the speedup achievable on GPU hardware. Unless you have a specific material system to benchmark, it is best to assess a range of systems and give a range of speedups. The speedup is dependent on the system size (electron count), total GPU memory, as well as details of the run. The kernel compute costs scale from linearly to effectively cubically with electron count times the batch size.  A large run with thousands of electrons might yield ~5x speedup depending on the CPU comparison (threads, socket, specific CPU & GPU). However, some systems that people wish to simulate don't fit in the memory of current GPUs, so even if there are sufficient electrons to get good speedup in principle, in practice they can't run easily. And GPUs can even be slower than CPUs - a run with twenty electrons will be hard to accelerate since, as compared to a large run with lots of electrons, the kernels are small and the run is proportionately branchier and will fit more in the cache of modern CPUs.

**Comment by zohimchandani** [comment]
@davidev886
