### ISSUE TITLE
Need a complex build in CI

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#468]
When dealing with PR #319, I realized that we'd better check complex build in CI.

**Comment by prckent** [comment]
@grahamlopez 

Suggested robot improvement: we have a CPU-rhea only robot and a GPU-rhea only robot instead of the current 3. Within each we build real, complex, and full/mixed precision. Seems like a quick patch given the evolving CI situation. The CPU jobs usually start quickly on rhea so I don't think this will hurt turnaround.

**Comment by grahamlopez** [comment]
Sounds like a good idea to me.

**Comment by ye-luo** [comment]
@grahamlopez When we have 3 builds in one CI job, can we print a bit info about the status of the three builds at the end of the log? If possible, we can first look at it before going to the log detail.

**Comment by grahamlopez** [comment]
Thinking about this a little bit more, the quickest (easiest for me) way to do this will likely result in a single build.log file for each CPU and GPU containing results for all build variants.

**Comment by ye-luo** [comment]
I think that is fairly enough.

**Comment by prckent** [comment]
Closed by #480
