### ISSUE TITLE
[3.17.0] Fails to find hdf5: HDF5 not found.  Set HDF5_ROOT

### ISSUE THREAD

**Issue by yurivict** [QMCPACK/qmcpack#4705]
**Describe the bug**
```
-- Unable to determine HDF5 C flags from HDF5 wrapper.
-- Could NOT find HDF5 (missing: HDF5_LIBRARIES) (found suitable version "1.12.2", minimum required is "1.10")
CMake Error at CMakeLists.txt:713 (message):
  HDF5 not found.  Set HDF5_ROOT
```

3.15.0 found hdf5 fine, but 3.17.0 fails.

hdf5 installs cmake files, so it should be easily found.

**System:**
 - system name: FreeBSD 13.2

**Additional context**
clang-15
hdf5-1.12.2_2

**Comment by prckent** [comment]
Thanks for the quick report Yuri. We are investigating. There seems to be something going on with certain versions of hdf5, cmake, and our use of them, possibly also the spack package manager installations as well. Assuming a common root cause, based on https://github.com/spack/spack/issues/35893 maybe 1.12.1 would work.
