### ISSUE TITLE
 QMCPACK Input Deck for Benchmarking on LLNL Systems

### ISSUE THREAD

**Issue by kulnaman** [QMCPACK/qmcpack#4784]
Hello QMCPACK team,

We're reaching out as systems researchers interested in using QMCPACK as a proxy application to study power and performance profiles on Lawrence Livermore National Laboratory (LLNL) Lassen system. While we are not domain scientists, we recognize the potential of QMCPACK in providing valuable insights into our research.

To facilitate our studies, we're looking for an input deck for Lassen system that would run in the ballpark of 5-10 minutes. Our goal is to understand the application's behavior under various power configurations without the run being too short or too lengthy.

Any guidance or resources you could provide in this regard would be greatly appreciated.

**Comment by prckent** [comment]
Just noticed this, sorry!

The general strategy would be to run the performance tests and then adapt the generated files. The performance tests as written do not get peak performance (on GPU systems) and are initialization heavy, since they are only a few minutes long. Then one can add more steps per block to reduce initiation fraction and the expense of more runtime. For GPU systems you need to manually (write a script) scan runs with increasing batch size to get enough GPU occupancy. Depending on your interests pick one or a few of the performance-NiO-*-batched_driver* ones. The aNNN and eNNN in the name are the atom and electron counts respectively. 

Hope this helps.

**Comment by prckent** [comment]
Please reopen or make a new issue if you have any further questions.
