### ISSUE TITLE
A example form qmcpack3.11.0 tests runs wrong

### ISSUE THREAD

**Issue by huangxxxxxxxx** [QMCPACK/qmcpack#4832]
**Describe the bug**
The qmcpack version is 3.11.0, when I run a example which from qmcpack-3.11.0/tests/molecules/H2_ae, some errors are appear. the errors are follows

![d865bad296e1e6cebd7512f9d28adbc](https://github.com/QMCPACK/qmcpack/assets/145572447/23c07c5b-0ab3-4699-94d5-24c8abecc877)

**Comment by prckent** [comment]
You are seeing a warning about updates to the XML. It is not a fatal error. If this is the only issue that you see in the output, then the run should still be good.

We are in the process of updating the input formats to be more consistent and importantly more verifiable. Older versions of the code do minimal checking.

NEXUS is kept updated to produce inputs that the version of QMCPACK it is released with expects. This avoids both warnings and errors due to changes. Please use the newest release if you are able to.
