### ISSUE TITLE
Integration test: 3-body Jastrow

### ISSUE THREAD

**Issue by jtkrogel** [QMCPACK/qmcpack#573]

**Comment by ye-luo** [comment]
For the moment, we have the H2O example testing JeeI. But I prefer to have an optimization test with J3. @jtkrogel Could you transfer the ownership of this issue to me?

**Comment by jtkrogel** [comment]
Is PBC not distinct?  I guess I would expect differences in distance calculations to be picked up elsewhere.  Transferring ownership.

**Comment by ye-luo** [comment]
Correct. BC is handled within distance tables.

**Comment by prckent** [comment]
I think we need a J3 test in PBC splines. Something like a single primitive cell of NiO for consistency with the performance tests, and a system where the J3 contribution is non-negligible. This will be essential to test any GPU J3 implementation unless the yet to be found GPU J3 creator also writes a Gaussian basis implementation (CPU bypass or GPU) based on @anbenali 's yet to be merged CPU-side rewrite :-)

**Comment by ye-luo** [comment]
[nightly tests](https://cdash.qmcpack.org/CDash/testSummary.php?project=1&name=short-monoO_1x1x1_pp-vmc_sdj3-1-16&date=2018-01-25) shows all the CPUs are fine and GPUs fail as inteded. I gave up NiO mainly because of the not small h5 size even for a small cell. On monoO, the energy gain from J3 is distinguishable.
@prckent can we close this ticket?

**Comment by prckent** [comment]
To test J3 sensibly we need a system with non-negligible J3 contribution. The test for O is a start but would not let us find e.g. a numerical problem due to optimizations. For NiO we need the smaller cell for the performance tests, as discussed. Then the J3 test can run if the wavefunction is available.
