### ISSUE TITLE
Improve the implementation of population control

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#609]
There are a few performance bottlenecks spotted in the population control implementation.
All these bottlenecks amplify the load imbalance among MPI ranks.

This issue lists the upcoming PRs to address this issue
1, The container std::vector with aligned allocator used by PooledMemory is slower than std::vector with default allocator. This is a performance regression comparing to v3.3.0. Solution: replace std::vector with our Vector class.
2, The cost in 1 was mainly due to frequent allocation and deallocation. A new algorithm will be used to recycle bad walkers. It also avoids sudden temporal high memory needs.
3, A new algorithm will be added to send/recv identical walkers in batches. isend/recv will also help reducing serialization. The old implementation mentioned as async in #461 can be removed. This part of improvement can also be used for reconfiguration.

more details will be given in each PR.

A NiO S64 run on Theta 1024 KNL nodes. 1024 MPI ranks with 64 threads. Using ynamic population control. On average, 63 walkers per node. Intel compiler 18, Cray MPI.
version DMC block CPU
v3.3.0 179.8 sec 
develop about 2x slower than v3.3.0. I don't have the exact run.
new 69.4 sec
The new run was a survey run with extra barriers. The final version has no barriers and saves a few seconds. With all the changes, the branching cost goes down to 7% level.

**Comment by prckent** [comment]
@ye-luo Thanks for catching these. Please can you update your Issue to give full details of the runs for which you give timings? e.g. walker count, MPI task count, which run (NiO performance, ideally), which computer system/mpi, where tested, which versions of code etc.

I would like to understand the history of these problems so that we can catch them sooner in future.

**Comment by ye-luo** [comment]
@prckent run details updated.

**Comment by lshulen** [comment]
This is quite interesting.  The factor of 2 performance difference for a calculation so close to 1 walker per thread suggests the interpretation that in the first case some thread is forced to propagate 2 walkers whereas in the second case all threads stay below 1 walker per thread.  

Are there enough steps / blocks in your run for you to be sure that this is a persistent problem rather than a statistical fluke?  Another way of asking the question, do you still see a large population control cost if you have ~50 walkers / node instead of ~63?

**Comment by prckent** [comment]
The performance history should be trackable in cdash...

**Comment by ye-luo** [comment]
@lshulen I set the warm up steps longer than the run so the tight population control is always effective and the number of walkers never goes beyond 64 per node, confirmed by dmc.dat.
@prckent This is an imbalance issue and shows up significantly when you have many ranks which we can't do with ctest now.

**Comment by ye-luo** [comment]
I thought the improvement is more beneficial to CPU but actually also the GPU run gets a huge boost.
NiO 128 atom cell on 1024 nodes of titan. Block time drops from 86 sec to 52 sec.

**Comment by ye-luo** [comment]
All the changes discussed in this PR have been merged.
