### ISSUE TITLE
sed warning at make

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#695]
I got the following warning on Titan.
Coming from `src/CMakeLists.txt`
```
sed: invalid option -- 'E'
Usage: sed [OPTION]... {script-only-if-no-other-script} [input-file]...
...
```

**Comment by PDoakORNL** [comment]
https://stackoverflow.com/questions/3139126/whats-the-difference-between-sed-e-and-sed-e

Its apparently been support by gnu sed for some time but not always.
the newest gnu-sed source code supports -E and implies it will become part of the POSIX standard.
For now i think we should just branch for Darwin since -r will work everywhere that isn't BSD.

**Comment by prckent** [comment]
@grahamlopez more reason to get CI working on Titan et al.

**Comment by markdewing** [comment]
The consequence will be there is no git commit subject in the git-rev.h file on Titan.
