### ISSUE TITLE
CMake: Many intrinsics not detected with GNU compilers

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#76]
Intrinsics such as sincos are not being detected with the gcc family on oxygen and billmp1. This hurts performance, particularly in the nightly testing. The intrinsics are being detected when the Intel compiler family is used on the same system. Likely a libraries/options/default language level issue.

Check cdash for configuration failures and widely differing test performance between compilers.

**Comment by ye-luo** [comment]
Not fully understand your question. If you refer to sincos intrinsics, they are part of the MKL. On GNU+MKL tests, I thought we have already gain back most of the performance in ticket #9 unless you mean something else?

**Comment by prckent** [comment]
Read the output of the configure in cdash even for gcc+mkl. The checks are failing.

-- Looking for sincos
-- Looking for sincos - not found
-- Looking for round
-- Looking for round - not found
-- Looking for floor
-- Looking for floor - not found
-- Looking for posix_memalign
-- Looking for posix_memalign - found
-- Looking for pow
-- Looking for pow - not found
-- Looking for sqrt
-- Looking for sqrt - not found

**Comment by ye-luo** [comment]
The same issue also exists on hyperion.alcf.anl.gov.

There are 6 checks in the CMake.
CHECK_FUNCTION_EXISTS(sincos HAVE_SINCOS)
CHECK_FUNCTION_EXISTS(round HAVE_STD_ROUND)
CHECK_FUNCTION_EXISTS(floor HAVE_FLOOR)
CHECK_FUNCTION_EXISTS(posix_memalign HAVE_POSIX_MEMALIGN)
CHECK_FUNCTION_EXISTS(pow HAVE_POW)
CHECK_FUNCTION_EXISTS(sqrt HAVE_SQRT)

Only sincos is performance critical. sincos is not in c/c++ standard but glibc libm, ibm libmass, intel math library have it.
When your MPI wrapper with GNU has -lm, the check passes. In your case -lm is not included in your wrapper. However, libm is anyway added via libhdf5 on Linux.
On Mac, there is no libm but another math library. So it is a bit difficult to have a clean solution. @berrill  perhaps has better ideas handling this.

HAVE_STD_ROUND should be cleaned. Only 1 place left. 
HAVE_FLOOR, HAVE_POW and HAVE_SQRT can be removed. No more used anywhere in the code.
I will commit this part of change soon.

**Comment by prckent** [comment]
@ye-luo Once HAVE_SINCOS is set to false we use our own function that calls sin() then cos(). Good catch about Hyperion - this probably explains why some of the KNL tests are so slow compared to the Xeon builds on oxygen.

**Comment by markdewing** [comment]
The narrow fix to the issue to make sure libm is linked while checking for function existence. 
Using `SET(CMAKE_REQUIRED_LIBRARIES m)` before the function checks seems to work on an x86 linux machine with GCC.  (I don't know what the effect is on other platforms is, it would need to be tested)

However, I don't think sincos vs. seperate sin/cos is the real performance issue. A microbenchmark on my laptop show sincos takes 71ns and separate sin/cos calls take 80ns.  (One interesting side note - at first in the microbenchmark there were separate sin/cos calls with the same argument and the gcc optimizer was coalescing the two into a single sincos call.  The fix was to adjust one of the arguments slightly to foil the optimizer.)

I suspect #63 is a bigger issue for performance.  There are also three types of vectorization/SIMD usage to consider
1. Calls of a single argument optimized for a particular SIMD level (eg. __sin_avx).
2. Short, fixed vectors (usually around SIMD unit length). This computes like 4 or 8 values at a time.   Intel's SVML or the glib mvec library fall into this category.  These are usually called by compiler auto-vectorization.   Compilation of the fallback eval_e2iphi loops should be vectorizable this way.
3. Long, arbitrary length vectors.  These require explicit calls in the source code.  VML (note, different from SVML) and massv fall into this category, and detecting and using these libraries is what issue #63 is about.

**Comment by ye-luo** [comment]
I don't think Mac uses libm. Did your write sin()/cos() or std::sin()/std::cos() in your microbenchmark?

**Comment by prckent** [comment]
- Mac performance is not really relevant.
- The GCC+MKL builds on oxygen correctly use Intel SVML. Lib mvec is not available/usable due to the libc version on oxygen (this is tied in with the Linux distribution and unlikely to change for a long while).
- SVML is being detected properly on Hyperion with Intel compilers 
- Both Hyperion (Intel builds) and oxygen (GCC builds) show very large performance differences compared to the Intel builds on oxygen. Of course these are edge cases, but KNL should not be that bad, neither should GCC.
- Improving performance here would greatly help our test times.

**Comment by markdewing** [comment]
@ye-luo .  I just tried std::sin, and it calls the same underlying function (sin@@GLIBC_2.2.5)
These tests were all with doubles.  I didn't test floats.

**Comment by ye-luo** [comment]
@prckent what you referred is VML not SVML. SVML is part of Intel compiler. VML is part of MKL.

**Comment by prckent** [comment]
@ye-luo Corrected

**Comment by ye-luo** [comment]
We have cleaned up all the intrinsic checks.
Aboout vector math, I found the vectorization capability of gcc remains quite limited. As our major production compiler is not gcc, I will leave this as `won't fix`.
