### ISSUE TITLE
Orbitals in backflow tests not normalized

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#804]
https://cdash.qmcpack.org/CDash/testDetails.php?test=2061411&build=21910
@Paul-St-Young is your modification to the cusp make the orbital denormalized?

**Comment by Paul-St-Young** [comment]
Yes, the cusp correction changes the normalization of every orbital by the same amount.

**Comment by prckent** [comment]
We could alternatively check for a *consistent* normalization. i.e. Check all orbital norms are consistent with the first one.

This would increase flexibility, e.g. due to changes in the cusp scheme, a code that normalizes the orbitals to the number of basis functions etc.

**Comment by ye-luo** [comment]
The orbital loading is distributed over MPI and norm check is on-the-fly.
The converter should do the black magic not inside QMCPACK.

**Comment by Paul-St-Young** [comment]
@ye-luo yes I can make my converter re-normalize the orbitals so that the CDash tests will pass.

In terms of design, I would prefer a user flag to turn off the orbital norm check. The current norm check is simple and good for catching bugs. If would just be good to be able to turn it off when a developer is doing non-standard stuff.
