### ISSUE TITLE
Creating a feature table in the manual

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#870]
Based on #869 , lets discuss what needs to be in the table.

I think this table will be useful for users and it might also help us drive decisions

Starting with columns only:

MPI, OpenMP
SoA CPU, AoS CPU, CUDA
full double, mixed, complex (+mixed complex?)

**Comment by ye-luo** [comment]
We don't want a long table.  For example if a feature doesn't support OpenMP, just add  comment instead of a column. The distinction between real and complex is also small

| features | CPU AoS | CPU SoA | CUDA | Comments |
| --- | :---: | :---: | :---: | --- |
| Methods | | | | |
| VMC | T | T | T | |
| DMC | T | T | T | Size consistent T move only on CPU |
| RMC | T | T | T | |
| Optimization | T | T | T | CPU mixed precision is not supported|
| Boundary conditions | | | | |
| ppp | T | T | T | |
| ppn | T | T | F | |
| pnn | T | T | F | |
| nnn (open) | T | T | T | |
| SPOs | | | | |
| Spline | T | T | T | Support both real and complex |
| Hybrid orbital representation | F | T | F | Support both real and complex |
| LCAO | T | T | F | Complex is not supported |
| Wavefunction components | | | | |
| Slater Det | T | T | T | |
| Multi Det | T | T | F | |
| One body Jastrow | T | T | T | |
| Two body Jastrow | T | T | T | |
| Three body Jastrow | T | T | F | ion-electron-eletron type |

**Comment by jtkrogel** [comment]
In addition to this, three more tables may be warranted as they will each identify holes missing in the one proposed above.

1) Wavefunctions (rows: SD/MD/BF/J1/J2/J3 etc) vs. methods (cols: VMC/DMC/RMC/OPT etc)
2) Estimators vs. methods
3) Estimators vs. wavefunctions

Versions of these tables should be made for AoS, SoA, and CUDA separately (probably times full/mixed and real/complex since this is the reality of the code).  

The wide divergence between the tables should motivate more work on bringing the branches into tighter sync and ending up with fewer branches overall.

**Comment by prckent** [comment]
I think that this can be closed.

We may have to start a new version to track the development of the new offload code, but the basic idea is that eventually we won't need a table since all features will be available where the physics is valid.
