### ISSUE TITLE
Problems with unicode characters in manual and some LaTeX installations

### ISSUE THREAD

**Issue by prckent** [QMCPACK/qmcpack#873]
Some LaTeX installs will not build the manual successfully due to unicode characters in the source .tex files.  The characters appears to be mostly pipes and dashes in the tutorials and could be removed or replaced.  (Discovered with a fresh TeX live 2018 install on os x.)

```

! Package inputenc Error: Unicode character │ (U+2502)
(inputenc)                not set up for use with LaTeX.

See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
 ...

l.46 │

```

**Comment by ye-luo** [comment]
It also hits me 2 minutes ago with Tex live 2018 on linux.

**Comment by prckent** [comment]
I think the preferred route  is to remove the unicode, as opposed to tweaking the package use or adding definitions - we need to move in a direction easier to convert to html or to use a markup language. 

@ye-luo Do you agree?

**Comment by ye-luo** [comment]
I also prefer removing than fixing.

**Comment by jtkrogel** [comment]
Agree.  Prefer replacement with nearest available ASCII (which may constitute a removal in some cases).

**Comment by PDoakORNL** [comment]
Notable TeX Live changes
Two changes may be immediately noticeable. The first is that the default encoding for input sources to LaTeX has changed from ISO Latin 9 to UTF-8 Unicode. Standard ASCII files satisfy both encoding rules and thus are accepted as usual. Latin 9 is an encoding standard that adds to ASCII various accents, umlauts, and special characters like upside down question marks used in Western Europe. From 2018 on, such input files require a LaTeX header line

 
 	\usepackage[latin9]{inputenc}

UTF-8 is an encoding standard for full unicode, which can simultaneously encode most scripts used across the world: Roman, Arabic, Chinese, Hebrew, Hieroglyphics, Japanese, etc. Until now, Latex sources using this encoding required the header line

	\usepackage[utf8]{inputenc}

but this line is now optional because UTF-8 is the default.
